---
# Configure ansible-buildah

- name: service is enabled and started
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  become: true
  loop: "{{ ansible-buildah_services_enable }}"
  when: ansible-buildah_enable_service
